# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "tucue"
require "minitest/autorun"
require "tmpdir"
require "fileutils"

module TestHelpers
  module_function

  # True if an mpv executable is available on PATH.
  def mpv_available?
    ENV["PATH"].to_s.split(File::PATH_SEPARATOR).any? do |dir|
      File.executable?(File.join(dir, "mpv"))
    end
  end

  # Write a minimal silent PCM WAV of +seconds+ to +path+ and return it.
  # Generated by hand so the tests need no external encoder (ffmpeg, etc.).
  def write_silent_wav(path, seconds: 2, sample_rate: 8000)
    samples = seconds * sample_rate
    data_size = samples * 2 # 16-bit mono

    File.open(path, "wb") do |f|
      f.write("RIFF")
      f.write([36 + data_size].pack("V"))
      f.write("WAVE")
      f.write("fmt ")
      f.write([16, 1, 1, sample_rate, sample_rate * 2, 2, 16].pack("VvvVVvv"))
      f.write("data")
      f.write([data_size].pack("V"))
      f.write("\x00\x00".b * samples)
    end
    path
  end
end
